### ISSUE TITLE
[DJs Application Forums] djzth-utils doesn't always mention "@death jester member"

### ISSUE THREAD

**Issue by lyledouglass** [waggz81/djzth-utils#4]
Don't have much info on this one. Latest occurrence is in the `Slackfist - Stormrage` forum thread. I don't see anything explicitly in the code that does this. Wondering if there needs to be a time wait before it tries posting?

**Comment by waggz81** [comment]
https://github.com/waggz81/djzth-utils/blob/7fe5291fa62b612497f0159cf3df71ade0d16c99/index.ts#L123 is the function

**Comment by waggz81** [comment]
```
<@&748569132575883436>
DiscordAPIError: Cannot message this thread until after the post author has sent an initial message.
    at RequestHandler.execute (/home/rocky/djzth-utils/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RequestHandler.push (/home/rocky/djzth-utils/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at ThreadChannel.send (/home/rocky/djzth-utils/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15) {
  method: 'post',
  path: '/channels/1053908122575585310/messages',
  code: 40058,
  httpStatus: 403,
  requestData: {
    json: {
      content: '<@&748569132575883436>',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
```

**Comment by waggz81** [comment]
i think this is fixed? there's a 3s delay now
